# Generated by Django 6.0.3 on 2026-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='motivo',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
