# Generated by Django 6.0.3 on 2026-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_movimentacaoestoque_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', 'Matéria Prima (Produção)'), ('uso_consumo', 'Uso e Consumo (Limpeza/Escritório)'), ('ativo_imobilizado', 'Ferramentas e Ativos (Tesouras/Máquinas)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('m', 'Metros'), ('cm', 'Centímetros'), ('rolo', 'Rolo'), ('litro', 'Litro')], max_length=10),
        ),
    ]
