# Generated by Django 6.0.3 on 2026-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data_transacao'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('venda', 'Venda de Serviço/Comanda'), ('estoque', 'Compra de Material/Insumo'), ('limpeza', 'Produtos de Limpeza'), ('infra', 'Infraestrutura (Luz/Água/Internet)'), ('aluguel', 'Aluguel'), ('salario', 'Pró-labore/Salários'), ('marketing', 'Marketing/Anúncios'), ('outros', 'Outros Gastos')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(help_text='Ex: 5m de Jeans ou Material de Limpeza', max_length=255),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita (Entrada)'), ('despesa', 'Despesa (Saída)')], max_length=10),
        ),
    ]
