# Generated by Django 6.0.3 on 2026-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='origem',
            field=models.CharField(blank=True, choices=[('san_marino', 'San Marino'), ('nossa_escola', 'Nossa Escola'), ('colegio_torres', 'Colégio Torres'), ('indicacao', 'Indicação'), ('avulso', 'Avulso'), ('google', 'Google'), ('instagram', 'Instagram')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('reforma', 'Reforma'), ('uniforme', 'Uniforme'), ('confeccao', 'Confecção')], max_length=20, null=True),
        ),
    ]
