# Generated by Django 6.0.3 on 2026-04-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_comanda_origem_itemcomanda_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
